# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SamchiBase - 삼치의 로봇공방
email: samchi.robot@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Samchibase is an archive that records the information I need as I develop. 
  It mainly covers the theory of robots and sensors and information on open source based development.
baseurl: / # the subpath of your site, e.g. /blog
url: https://samchirobot.github.com # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  samchirobot

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
author: samchirobot

paginate: 5
paginate_path: "/posts/page:num/"
permalink: "/:year/:month/:day/:title/"
category_list: [Robotics, Linux, ROS, Estimation, DSP, Sensor]

encoding: utf-8
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
